---
title: "Fig 4: Use case 1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, fig.width=8, fig.height=5)
```

```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(reshape2)
library(yaml)
library(ggplot2)
library(lemon)
```


```{r}
meta <- data.frame(read_csv("/storage/mariiac/ligo_paper_figures/use_case_2/main_data/inst1/exported_dataset/airr/metadata.csv"))
lr_path <- "/storage/mariiac/ligo_paper_figures/use_case_2/LR"
fname <- "inst1/signal_label_all_assessment_performances.csv"
```

# Accuracy figure

```{r}
df <- data.frame()

for (i in 1:10) {
  strat <- read_csv(file.path(lr_path, i, "lr_strat", fname))
  strat$sample <- i
  strat$split_type <- "stratified"
  random <- read_csv(file.path(lr_path, i, "lr_random", fname))
  random$sample <- i
  random$split_type <- "random"
  
  tmp <- rbind(strat, random)
  df <- rbind(df, tmp)
}

df <- data.frame(df)

```

```{r, fig.width=6.5, fig.height=5}
# get medians
df_melt <- melt(df, id.vars = c("hp_setting", "split_type", "split", "optimal", "sample"))

df_melt <- df_melt[df_melt$hp_setting == "4mer_LR", ]

df_median <- df_melt %>% group_by(split_type, variable) %>%
  summarise(median = round(median(value), 2))
```

```{r}
ggplot(df_melt, aes(x = as.factor(variable), y = value)) +
  facet_grid(~ split_type ) +
  geom_boxplot() +
  geom_jitter(size = 0.8) +
  geom_text(data = df_median, aes(x = as.factor(variable), y = median, label = median, color ="red"), 
              position = position_dodge(width = 0.8), size = 4, vjust = -.9, hjust = -.05) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        panel.grid.minor = element_line(size = 0), panel.grid.major = element_line(size = 0), 
        axis.text=element_text(color="black")) +
  theme_classic() +
  xlab("Logistic regression performance") 
```


# Coefficients figure
```{r}
df <- data.frame()

for (i in 1:10) {
  strat <- read_yaml(file.path(lr_path, i, "lr_strat", fname))
  strat_coefs <- data.frame(coefs = strat$coefficients, 
                            kmers = strat$feature_names)
  strat_coefs$sample <- i
  print(head(strat_coefs ))
  strat_coefs$split_type <- "stratified"
  random <- read_yaml(file.path(lr_path, i, "lr_random", fname))
  random_coefs <- data.frame(coefs = random$coefficients, 
                             kmers = random$feature_names)
  random_coefs$sample <- i
  random_coefs$split_type <- "random"
  print(head(random_coefs))
  
  
  tmp <- rbind(strat_coefs, random_coefs)
  df <- rbind(df, tmp)
}

df <- data.frame(df)
```

```{r}
# get top 10 largest (by modulo) coefs on average

df_mean_coefs <- df %>% group_by(kmers, split_type) %>%
  summarise(mean_abs_coefs = mean(abs(coefs))) %>%
  arrange(desc(mean_abs_coefs))

top_random_kmers <- head(df_mean_coefs[df_mean_coefs$split_type == "random", ]$kmers, 20)
top_strat_kmers <- head(df_mean_coefs[df_mean_coefs$split_type == "stratified", ]$kmers, 20)


df_top <- data.frame(rbind(df[df$split_type == "random" & df$kmers %in% top_random_kmers, ], 
                df[df$split_type == "stratified" & df$kmers %in% top_strat_kmers, ]))

df_top <- df_top[order(abs(df_top$coefs)), ]
```

```{r}
df_top_mean <- df_top %>% group_by(kmers, split_type) %>%
  summarise(mean = mean(coefs), sd = sd(coefs)) %>%
  arrange(desc(mean)) %>%
  data.frame

df_top_mean$tag <- "other"
df_top_mean$tag[df_top_mean$kmers == "AAAA"] <- "AAAA"
df_top_mean$tag[df_top_mean$kmers == "AACA"] <- "AACA"
df_top_mean$tag[df_top_mean$kmers == "AAGA"] <- "AAGA"
df_top_mean$tag[df_top_mean$kmers == "AANA"] <- "AANA"


ggplot(df_top_mean, aes(x = reorder(kmers, -abs(mean)), y = mean, fill = tag)) +
  facet_rep_wrap(. ~ split_type, scales='free_x', repeat.tick.labels = T) +
  geom_bar(stat="identity", width = 0.7) + 
  geom_errorbar( aes(x=kmers, ymin=mean-sd, ymax=mean+sd), width=.4, size = 0.3) +
  theme_minimal() +
  scale_fill_manual(values = c("AAAA" = "#E6332A", "AAGA" = "#1D71B8", "AACA" = "#008D36", "AANA" = "#F39200", "other" = "grey")) +
  scale_y_continuous(breaks=seq(-0.4, 1.2, 0.2)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 13), 
        axis.text.y = element_text(size = 10),
        panel.grid.minor = element_line(size = 0.1), panel.grid.major = element_line(size = 0.2), 
        axis.text=element_text(color="black"))

ggsave(filename = file.path("/storage/mariiac/ligo_paper_figures/use_case_2/coefs.png"), width = 8, height = 4, device='png', dpi=700)
  
```



